3405000/team201-frontend

- src/app/app-routing.module.ts
- src/app/pages/store/components/event/event.component.html
- src/app/pages/store/components/event/event.component.ts
- src/app/pages/store/components/menu/menu.component.html
- src/app/pages/store/components/menu/menu.component.spec.ts
- src/app/pages/store/components/menu/menu.component.ts
- src/app/pages/store/components/review-list/review-list.component.html
- src/app/pages/store/components/review-list/review-list.component.ts
- src/app/pages/store/components/store-info/store-info.component.html
- src/app/pages/store/components/store-info/store-info.component.ts
- src/app/pages/store/services/event.service.ts
- src/app/pages/store/services/review.service.ts
- src/app/pages/store/services/store.service.ts
- src/app/pages/store/store-routing.module.ts
- src/app/pages/store/store.module.ts
- src/app/pages/store/store.page.html
- src/app/pages/store/store.page.ts
closed #3 
<br/>
- 03.04 참조
https://www.notion.so/Frontend-1ac8923feb4b803395bee7b7d795aab5?pvs=4
- 피드백 요청
> [feat] #3 - store 폴더 구조 및 컴포넌트 생성

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/model/common/api-response.interface.ts
- src/app/model/reviews/read-all-reviews.interface.ts
- src/app/pages/reviews/review-list/review-list.component.html
- src/app/pages/reviews/review-list/review-list.component.ts
- src/app/pages/reviews/review/review.component.html
- src/app/pages/reviews/review/review.component.ts
- src/app/pages/reviews/reviews.module.ts
- src/app/pages/reviews/reviews.page.html
- src/app/services/reviews.service.ts
closed #9 
<br/>
- httpclient 연결 -> DB 데이터 받아오기 테스트 완료
- review component, review-list component, review-page 를 나누어 생성하고 연결
- 코드짜다보니 review 백엔드 다듬을 게 많이 보여서, 일단 여기까지 머지하고 백엔드 다시 수정하러 갑니다
> [design] #9 - review httpclient db 연결 확인

- src/app/model/replies/read-reply.interface.ts
- src/app/model/reviews/read-all-reviews.interface.ts
- src/app/model/reviews/read-review.interface.ts
- src/app/pages/reviews/review-list/review-list.component.html
- src/app/pages/reviews/review-list/review-list.component.ts
- src/app/pages/reviews/review/review.component.html
- src/app/pages/reviews/review/review.component.ts
- src/app/services/reviews.service.ts
closed #13 
<br/>
- 백엔드에서 수정한 review, reply dto 및 메서드 반영
- review, review-list ui에 데이터 불러오기
- 날짜 및 수정여부 getter 생성
- 아직 프사, 닉네임(사용자), 리뷰이미지 등 백엔드 미구현 사항이 있음
> [feat] #13 - review 백엔드 수정사항 반영 및 ui 배치

- src/app/app-routing.module.ts
- src/app/model/common/request-status.enum.ts
- src/app/model/manager-requests/read-manager-request.interface.ts
- src/app/pages/admin/admin-routing.module.ts
- src/app/pages/admin/admin.module.ts
- src/app/pages/admin/admin.page.html
- src/app/pages/admin/admin.page.ts
- src/app/pages/admin/manager-request-list/manager-request-list.component.html
- src/app/pages/admin/manager-request-list/manager-request-list.component.ts
- src/app/pages/admin/manager-request/manager-request.component.html
- src/app/pages/admin/manager-request/manager-request.component.ts
- src/app/pages/reviews/review/review.component.html
- src/app/pages/reviews/review/review.component.ts
- src/app/pages/reviews/reviews.module.ts
- src/app/pages/reviews/reviews.page.ts
- src/app/services/manager-requests.service.ts
closed #15 
<br/>
- ManagerRequest component, page, interface, service 생성
- 뷰에서 read 데이터 연결 화긴..
> [feat] #15 - ManagerRequest 구성요소 생성

- src/app/admin/manager-request/manager-request.component.ts
- src/app/admin/request-list/request-list.component.ts
- src/app/admin/store-request/store-request.component.ts
closed #
<br/>
- 폴더 구조 변경으로 인한 경로 오류수정
- 피드백 요청
> [fix] #20 - fix path errors

- src/app/services/nearby-stores.service.ts
closed #41 
<br/>
- 변경된 인터페이스명을 NearbyStoresService에 반영
- getAllStores 및 getStoreById의 반환 타입 수정
- 올바른 인터페이스를 import하도록 수정
- 피드백 요청
> fix: 인터페이스명 변경으로 인한 서비스 코드 수정

- src/app/admin/components/manager-request/manager-request.component.ts
- src/app/admin/components/request-list/request-list.component.ts
- src/app/admin/components/store-request/store-request.component.ts
- src/app/admin/pages/admin/admin.page.ts
- src/app/admin/pages/manager-request-page/manager-request-page.ts
- src/app/admin/pages/store-request-page/store-request-page.ts
- src/app/app-routing.module.ts
- src/app/manager/components/manager-request-list/manager-request-list.component.html
- src/app/manager/components/manager-request-list/manager-request-list.component.ts
- src/app/manager/components/manager-request/manager-request.component.html
- src/app/manager/components/manager-request/manager-request.component.ts
- src/app/manager/manager-routing.module.ts
- src/app/manager/manager.module.ts
- src/app/manager/pages/manager/manager.page.html
- src/app/manager/pages/manager/manager.page.ts
- src/app/manager/pages/my-manager-request/my-manager-requests.page.html
- src/app/manager/pages/my-manager-request/my-manager-requests.page.ts
- src/app/model/manager-requests/create-manager-request.interface.ts
- src/app/my-page/components/my-info/my-info.component.ts
- src/app/my-page/components/my-review-list/my-review-list.component.ts
- src/app/my-page/pages/my-page/my-page.page.ts
- src/app/my-page/pages/my-reviews-page/my-reviews.page.ts
- src/app/reviews/review-list/review-list.component.ts
- src/app/reviews/review/review.component.ts
- src/app/services/manager-requests.service.ts
- src/app/services/users.service.ts
closed #43
<br/>
- manager home page
- manager my manager requests page (read)
- scss 삭제
- store request 관련은 user와 동일한 화면 사용하면 될듯해서 안햇습니다
- store request 구현 되면 manager는 storerequest와 manager request를 동시에 신청할 수 있도록 구현 예정
- manager request 신청 역시 map, store 페이지 구현 끝나면 연결해야할듯염
> [feat] #43 - manager home, my manager requests page 구현

- src/app/services/manager-requests.service.ts
> [fix] #46 - import 오류 수정

- src/app/app-routing.module.ts
- src/app/register/register-routing.module.ts
- src/app/register/register.module.ts
- src/app/register/register.page.html
- src/app/register/register.page.ts
- src/app/shared/model/auth/create-user.interface.ts
- src/app/shared/services/auth.service.ts
- src/app/shared/services/users.service.ts
closed #51 
<br/>
- 회원가입 페이지 구현
- 이메일 중복 검사 기능
- 추후 아래 기능/로직에 대해 회의 후 구현해야 할 듯.
1. 관리자 선택 시 인증 방식 (관리자 비밀번호를 통한 검증 방식 생각 중)
2. 회원가입 완료 시 로그인 페이지로 이동
> [feat] #51 - 회원가입 페이지 구현

- src/app/app.module.ts
- src/app/manager/manager-routing.module.ts
- src/app/manager/manager.module.ts
- src/app/manager/pages/manager/manager.page.html
- src/app/manager/pages/manager/manager.page.ts
- src/app/manager/pages/my-stores/my-stores.page.html
- src/app/manager/pages/my-stores/my-stores.page.ts
- src/app/shared/model/stores/read-store.interface.ts
- src/app/shared/services/stores.service.ts
closed #57 
<br/>
- 해당 매니저의 store 목록 불러오기 기능 구현 완료
- **주제 변경 이슈로 작업 일시 중단**
- 피드백 요청
> Feat/#57 [feat] #57 - 가게 정보 수정 기능 구현 (중단)

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/home/home.page.html
- src/app/register/register.page.ts
- src/app/shared/model/auth/create-user.interface.ts
- src/app/shared/model/auth/singin.interface.ts
- src/app/shared/services/auth.service.ts
- src/app/signin/signin-routing.module.ts
- src/app/signin/signin.module.ts
- src/app/signin/signin.page.html
- src/app/signin/signin.page.ts
closed #60 
<br/>
- 로그인 페이지 구현
- 회원가입 페이지와 리다이렉팅 구조 구현
- localhost:8100 페이지(기본 경로)를 로그인 페이지로 설정
- 피드백 요청
> [feat] #60 - login 페이지 구현

- src/app/shared/model/stores/read-store.interface.ts
- src/app/store/components/store-info/store-info.component.html
- src/app/store/components/store-request/create-store-request.component.ts
closed #71 
<br/>
백엔드에서 category 정보를 객체 형태({ category_id, category_name })로 반환하도록 변경됨에 따라, 프론트엔드 ReadStore 인터페이스 및 관련 컴포넌트 로직을 수정
- 피드백 요청
> [refactor] #71 - category 타입을 객체로 변경하고 store에 적용

- src/app/map/components/map.component.ts
- src/assets/naver-map/script.js
closed #74 
<br/>
데스크탑이나 노트북은 Wi-Fi 또는 IP 기반으로 위치를 추정하기 때문에 부정확하다.
GPS 사용해면 됨 (GPS는 정확도 ±5~50m 정도 오차 있음 / 특히 실내에서는 더 큼)
> [fix] #74 - 위치 처리 중복 코드 통합 및 마커 정확도 개선

- src/app/home/home.page.html
- src/app/home/home.page.ts
- src/app/shared/services/images.service.ts
closed #70 
<br/>
- 테스트 이미지 출력 생략하려 했으나, 참고용으로 냅두겠습니다.
- 피드백 요청
> [feat] #70 - S3에서 이미지 가져오기 기능 구현

- src/app/app-routing.module.ts
- src/app/manager/components/manager-request-list/manager-request-list.component.ts
- src/app/manager/components/search-store/search-store.component.html
- src/app/manager/components/search-store/search-store.component.ts
- src/app/manager/manager-routing.module.ts
- src/app/manager/manager.module.ts
- src/app/manager/pages/create-manager-request/create-manager-request.page.html
- src/app/manager/pages/create-manager-request/create-manager-request.page.ts
- src/app/manager/pages/my-manager-request/my-manager-requests.page.html
- src/app/manager/pages/my-manager-request/my-manager-requests.page.ts
- src/app/manager/pages/my-stores/my-stores.page.html
- src/app/manager/pages/my-stores/my-stores.page.ts
- src/app/my-page/components/my-info/my-info.component.ts
- src/app/my-page/components/my-review-list/my-review-list.component.ts
- src/app/reviews/pages/write-review/write-review.page.ts
- src/app/search/pages/search/search.page.html
- src/app/search/pages/search/search.page.ts
- src/app/search/search-routing.module.ts
- src/app/search/search.module.ts
- src/app/shared/model/manager-requests/create-manager-request.interface.ts
- src/app/shared/model/reviews/create-review.interface.ts
- src/app/shared/services/event.services.ts
- src/app/shared/services/manager-requests.service.ts
- src/app/shared/services/my-page.service.ts
- src/app/shared/services/search.service.ts
- src/app/shared/services/stores.service.ts
- src/app/shared/services/users.service.ts
- src/app/store/pages/edit-event/edit-event.page.ts
- src/app/store/pages/write-event/write-event.page.html
closed #73 
<br/>
- 점주신청서 생성, 나의 점주신청서 조회
- (점주신청서 승인 시) 나의 가게 목록 조회, 나의 가게로 연결
- 나의 가게 이벤트 생성, 수정, 삭제 기능
> [feat] #73 - Manager Request, Event CRUD

- src/app/map/components/map.component.html
- src/app/map/components/map.component.scss
- src/app/map/components/map.component.ts
- src/assets/naver-map/script.js
- src/assets/naver-map/styles.css
closed #80 
<br/>
- 실시간 위치 추적: 사용자의 위치를 watchPosition()으로 실시간 추적하도록 개선
- 마커 실시간 갱신: 위치 변경 시 기존 현위치 마커를 제거하고 새 위치로 갱신되도록 처리
- 토글 제거: 위치 추적 ON/OFF 버튼을 제거하고 항상 자동 추적되도록 변경
- 마커 커스터마이징: 빨간색 원형 + 애니메이션을 적용한 현재 위치 마커로 커스터마이징
> [feat] #80 - 실시간 위치 추적 및 현재 위치 마커 커스터마이징 기능 구현

- src/app/admin/components/manager-request/manager-request.component.html
- src/app/admin/components/store-request/store-request.component.html
- src/app/app-routing.module.ts
- src/app/reviews/pages/write-review/write-review.page.scss
- src/app/reviews/pages/write-review/write-review.page.ts
- src/app/shared/module/shared.module.ts
- src/app/shared/pipes/dateFormat.pipe.ts
- src/app/shared/pipes/relativeTime.pipe.ts
- src/app/shared/services/reviews.service.ts
- src/app/store/components/event/event.component.html
- src/app/store/components/reviews/reviews.component.html
- src/app/store/components/reviews/reviews.component.ts
- src/app/store/pages/event-list-page/event-list.page.html
- src/app/store/pages/event-list-page/event-list.page.ts
- src/app/store/pages/store-main-page/store.page.ts
> [refactor] #85 - 각종 오류 해결 및 프로젝트 구조/코드 정리

- src/app/home/home.module.ts
- src/app/home/home.page.html
- src/app/manager/pages/create-manager-request/create-manager-request.page.ts
- src/app/manager/pages/my-manager-request/my-manager-requests.page.ts
- src/app/manager/pages/my-stores/my-stores.page.ts
- src/app/reviews/components/review-list/review-list.component.ts
- src/app/shared/components/header-bar/header-bar.component.html
- src/app/shared/components/header-bar/header-bar.component.scss
- src/app/shared/components/header-bar/header-bar.component.ts
- src/app/shared/components/loggined/loggined.component.html
- src/app/shared/components/loggined/loggined.component.ts
- src/app/shared/module/shared.module.ts
- src/app/shared/services/auth.service.ts
- src/app/shared/utils/token.util.ts
- src/app/store/pages/write-event/write-event.page.ts
closed #84
<br/>
- 메인화면으로 가는 버튼
- 로그인된 사용자명 보이기
- 로그인 상태에 따른 로그인/로그아웃 버튼 <- 이거는 지금 로그인 했을 때만 home 페이지 접속이 돼서 확인이 불가능함
- 마이페이지 접속 버튼
> [feat] # 84 - 공통 헤더 구현

- src/app/home/home.page.ts
- src/app/manager/pages/my-stores/my-stores.page.ts
- src/app/map/components/map.component.ts
- src/app/store/pages/event-list-page/event-list.page.ts
closed #88 
<br/>
앞으로 가게 들어갈때
http://localhost:8100/stores/1
이런식으로 접속해야합니다
- 피드백 요청
> [refactor] #88 - store->stores로 변경

- src/assets/naver-map/script.js
closed #90 
<br/>
- script.js에서 fetch('/api/maps/client-id') 요청 시 Authorization 헤더 제거
- 서버 응답 상태 코드 확인 및 clientId가 없는 경우 예외 처리 추가
- JWT가 없어도 정상적으로 지도 API를 사용할 수 있도록 수정
- 피드백 요청
> [refactor] #90 - 인증 없이 지도 로딩 가능하도록 script.js fetch 로직 수정

- src/app/map/components/map.component.html
- src/app/map/components/map.component.scss
- src/app/map/components/map.component.ts
- src/app/shared/components/search-bar/search-bar.component.html
- src/app/shared/components/search-bar/search-bar.component.ts
- src/app/shared/services/maps.service.ts
- src/assets/naver-map/script.js
closed #92 
<br/>
- 키워드 기반 가게 검색 기능 추가 (readStoresByKeyword)
- 검색 결과 리스트 상단에 출력
- 결과 없을 경우 팝업(alert) 표시
- X 버튼 클릭 시 검색어 및 결과 초기화 처리 (ionClear 활용)
- 리스트 항목 클릭 시 해당 마커로 포커스 및 InfoWindow 열림
- 7자리 좌표 보정 로직 추가 (normalizeCoordinate 보완)
- 피드백 요청
> [feat] #92 - 키워드 검색 기능 및 검색 결과 리스트 표시 기능 추가

- src/app/home/home.page.html
- src/app/map/map.module.ts
- src/app/shared/components/header-bar/header-bar.component.ts
- src/app/shared/module/shared.module.ts
closed #95 
<br/>
- 기존에 별도 페이지로 분리되어 있던 지도 컴포넌트를 홈 화면으로 통합
- 피드백 요청
> feat: 홈 화면에 지도 컴포넌트 통합

- src/app/store/pages/store-detail-page/store-detail-page.html
- src/app/store/pages/store-detail-page/store-detail-page.ts
closed #98 
<br/>
재은이도 script.js 수정 중이라 수정된 부분 재은이한테 주고 나중에 재은이가 같이 올리기로 함
> [feat] #98 - store-detail-page에 현재 위치 및 가게 마커 표시 추가

- src/app/store/pages/edit-event/edit-event.page.html
- src/app/store/pages/edit-event/edit-event.page.ts
- src/app/store/pages/write-event/write-event.page.ts
closed #101 
<br/>
- 이벤트에서 날짜 입력을 받고 데이터를 불러와 보여주는데 에러가 발생한 것을 해결했습니다
- <img width="653" alt="image" src="https://github.com/user-attachments/assets/ce8e23cb-4db0-4823-b18e-ace4b46165a6" />
> [fix] #101 - 날짜 입력 폼 개선

- src/assets/naver-map/script.js
closed #104 
<br/>
createInfoWindowContent() 함수 내 카테고리 출력 방식 수정
> [fix] #104 - InfoWindow 카테고리 표시 오류 수정

- src/app/home/home-routing.module.ts
- src/app/manager/manager-routing.module.ts
- src/app/my-page/my-page-routing.module.ts
- src/app/register/register-routing.module.ts
- src/app/register/register.page.ts
- src/app/search/search-routing.module.ts
- src/app/signin/signin-routing.module.ts
- src/app/store/components/store-info/store-info.component.html
- src/app/store/pages/store-detail-page/store-detail-page.html
- src/app/store/pages/store-main-page/store.page.html
- src/app/store/pages/store-main-page/store.page.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/main.ts
closed #111
<br/>
- 가게 페이지에서 이벤트 목록으로 이동하는 버튼 위치 바꾸기
- 리뷰 작성하기 버튼 축소 및 리뷰 개수 보이기
- 가게 상세페이지 -> 가게정보 페이지 접속하면 헤더가 중복으로 나오는 문제 해결
- 가게 상세정보 카드 UI 개선
> [design] #111 - store page components UI 개선

- src/assets/naver-map/script.js
- src/assets/naver-map/styles.css
closed #115 
<br/>
- InfoWindow 가게 페이지 접속 버튼 위치 수정
> [fix] #115 - InfoWindow 가게 페이지 접속 버튼 위치 수정

- src/naver.d.ts
closed #123 
<br/>
- naver.d.ts에서 실수로 삭제된 세미콜론 복구
- 피드백 요청
> [fix] #123 - naver.d.ts 세미콜론 누락 수정

- src/app/map/components/map.component.ts
- src/naver.d.ts
closed #125
<br/>
- Ionic ToastController로 alert 대체
> [fix] #125 - map 위치 정확도 알림 기능 중복 실행 수정

- src/app/map/components/map.component.html
- src/app/map/components/map.component.scss
- src/app/map/components/map.component.ts
- src/app/shared/services/openai.service.ts
closed #130 
<br/>
- 사용자가 수동으로 날씨 입력 후 OpenAI API를 통해 음식 키워드 추천
- 추천 키워드 버튼 UI 추가
> feat: 날씨 기반 추천 키워드 UI 및 지도 연동 기능 추가

- src/app/my-page/components/my-info/my-info.component.scss
- src/app/shared/components/loggined/loggined.component.ts
- src/app/store/components/event/event.component.html
- src/app/store/components/event/event.component.scss
- src/app/store/components/event/event.component.ts
- src/app/store/pages/event-list-page/event-list.page.html
- src/theme-style.scss
- src/theme-typography.scss
closed #142
<br/>
- event component design
-
> [design] #142- event component design

- src/app/shared/model/reviews/read-review.interface.ts
- src/app/shared/services/my-page.service.ts
> [feat] #148 - 내 리뷰 조회 기능 구현

- src/app/manager/components/my-stores/my-stores.component.html
- src/app/manager/components/my-stores/my-stores.component.scss
- src/app/manager/components/my-stores/my-stores.component.ts
- src/app/manager/manager.module.ts
- src/app/manager/pages/manager/manager.page.html
- src/app/manager/pages/manager/manager.page.ts
- src/app/my-page/components/my-info/my-info.component.html
- src/app/my-page/components/my-info/my-info.component.scss
- src/app/my-page/components/my-review-list/my-review-list.component.html
- src/app/my-page/my-page.module.ts
- src/app/my-page/pages/my-page/my-page.page.html
- src/app/shared/components/header-bar/header-bar.component.html
- src/app/shared/components/loggined/loggined.component.ts
- src/app/shared/utils/token.util.ts
> [design] #151 - manager페이지 구현(1)

- src/app/shared/components/header-bar/header-bar.component.html
> [design] #154 - 헤더바 구분선 제거

- src/app/shared/module/shared.module.ts
> [fix] #157 - 오타 수정

- src/app/home/home.page.html
- src/app/manager/components/manager-request-list/manager-request-list.component.html
- src/app/manager/components/manager-request-list/manager-request-list.component.ts
- src/app/manager/components/manager-request/manager-request.component.html
- src/app/manager/components/manager-request/manager-request.component.scss
- src/app/manager/components/my-stores/my-stores.component.html
- src/app/manager/components/my-stores/my-stores.component.scss
- src/app/manager/components/my-stores/my-stores.component.ts
- src/app/manager/pages/edit-my-store/edit-my-store.page.html
- src/app/manager/pages/manager/manager.page.html
- src/app/manager/pages/my-manager-request/my-manager-requests.page.html
- src/app/my-page/components/my-info/my-info.component.ts
> [design] manager 페이지 구현(2)
